import type { Category, Subcategory } from '@raadi/catalog';
import {
  Armchair,
  Baby,
  Backpack,
  BedDouble,
  Beef,
  Bike,
  Book,
  Briefcase,
  Building2,
  Bus,
  Car,
  Caravan,
  CarFront,
  Cog,
  CookingPot,
  Dog,
  Dumbbell,
  Egg,
  Factory,
  Footprints,
  Gem,
  GraduationCap,
  Guitar,
  Hammer,
  HandHeart,
  HardHat,
  Headphones,
  Hotel,
  House,
  KeyRound,
  Lamp,
  LandPlot,
  Laptop,
  Luggage,
  Milk,
  Monitor,
  Motorbike,
  Music,
  Package,
  Palette,
  PartyPopper,
  PawPrint,
  Plane,
  Refrigerator,
  Scissors,
  Shirt,
  ShoppingBag,
  ShoppingCart,
  Shovel,
  Smartphone,
  Sofa,
  Sparkles,
  Sprout,
  Stethoscope,
  Store,
  Sun,
  Tablet,
  Tent,
  ToyBrick,
  Tractor,
  TreePine,
  Truck,
  Tv,
  UtensilsCrossed,
  Wheat,
  Wrench,
  type LucideIcon,
} from 'lucide-react';

export const CATEGORY_ICONS: Record<Category, LucideIcon> = {
  torget: ShoppingBag,
  bil: Car,
  eiendom: House,
  jobb: Briefcase,
  reise: Plane,
  // Somaliland
  vehicles: Car,
  property: House,
  phones: Smartphone,
  electronics: Sun,
  home: Sofa,
  fashion: Shirt,
  livestock: Beef,
  agriculture: Wheat,
  jobs: Briefcase,
  services: Wrench,
  business: Store,
  kids: Baby,
  'sports-hobbies': Dumbbell,
};

export const SUBCATEGORY_ICONS: Record<Subcategory, LucideIcon> = {
  elektronikk: Smartphone,
  mobler: Armchair,
  klaer: Shirt,
  sport: Bike,
  barn: Baby,
  hobby: Guitar,
  hage: Shovel,
  antikviteter: Palette,
  dyr: Dog,
  kjoretoyutstyr: Wrench,
  personbil: CarFront,
  varebil: Truck,
  motorsykkel: Motorbike,
  bobil: Caravan,
  salg: KeyRound,
  utleie: House,
  fritid: TreePine,
  tomt: LandPlot,
  nybygg: HardHat,
  naering: Building2,
  it: Laptop,
  helse: Stethoscope,
  bygg: HardHat,
  undervisning: GraduationCap,
  handel: ShoppingCart,
  transport: Truck,
  kontor: Briefcase,
  industri: Factory,
  reiseliv: UtensilsCrossed,
  hytteutleie: Tent,
  leilighet: BedDouble,
  pakkereise: Luggage,
  // Somaliland
  cars: CarFront,
  motorcycles: Motorbike,
  'trucks-buses': Bus,
  'auto-parts': Cog,
  'houses-rent': KeyRound,
  'houses-sale': House,
  land: LandPlot,
  'commercial-property': Building2,
  'short-stays': BedDouble,
  'mobile-phones': Smartphone,
  tablets: Tablet,
  'phone-accessories': Headphones,
  computers: Laptop,
  'solar-power': Sun,
  appliances: Refrigerator,
  'tv-audio': Tv,
  furniture: Sofa,
  kitchenware: CookingPot,
  'home-decor': Lamp,
  'mens-clothing': Shirt,
  'womens-clothing': Sparkles,
  shoes: Footprints,
  'jewellery-watches': Gem,
  bags: Backpack,
  camels: PawPrint,
  'goats-sheep': PawPrint,
  cattle: Milk,
  poultry: Egg,
  'farm-produce': Sprout,
  'animal-feed': Wheat,
  'farm-equipment': Tractor,
  'ngo-jobs': HandHeart,
  'it-jobs': Laptop,
  'sales-jobs': ShoppingCart,
  'driver-jobs': Truck,
  'teaching-jobs': GraduationCap,
  'health-jobs': Stethoscope,
  'construction-jobs': HardHat,
  'hospitality-jobs': Hotel,
  'office-jobs': Briefcase,
  'building-trades': Hammer,
  'transport-logistics': Truck,
  tutoring: Book,
  'it-services': Monitor,
  'events-catering': PartyPopper,
  'beauty-services': Scissors,
  'repair-services': Wrench,
  'business-equipment': Factory,
  wholesale: Package,
  'baby-gear': Baby,
  toys: ToyBrick,
  'kids-clothing': Shirt,
  'sports-equipment': Dumbbell,
  books: Book,
  'musical-instruments': Music,
};

/** Shortcuts on a category page: a label key under `categoryPage.shortcuts` and the filters it sets. */
export const SHORTCUTS: Partial<
  Record<Category, Array<{ key: string; params: Record<string, string> }>>
> = {
  torget: [
    { key: 'new', params: { condition: 'new' } },
    { key: 'under500', params: { priceMax: '500' } },
    { key: 'furniture', params: { subcategory: 'mobler' } },
  ],
  bil: [
    { key: 'electric', params: { subcategory: 'personbil', fuel: 'electric' } },
    { key: 'automatic', params: { subcategory: 'personbil', gearbox: 'automatic' } },
    { key: 'awd', params: { subcategory: 'personbil', drivetrain: 'awd' } },
    {
      key: 'recent',
      params: { subcategory: 'personbil', yearMin: String(new Date().getFullYear() - 3) },
    },
    { key: 'lowMileage', params: { subcategory: 'personbil', mileageMax: '50000' } },
  ],
  eiendom: [
    { key: 'apartments', params: { subcategory: 'salg', propertyType: 'apartment' } },
    { key: 'houses', params: { subcategory: 'salg', propertyType: 'house' } },
    { key: 'threeBedrooms', params: { subcategory: 'salg', bedroomsMin: '3' } },
    { key: 'freehold', params: { subcategory: 'salg', ownership: 'freehold' } },
  ],
  jobb: [
    { key: 'fullTime', params: { employmentType: 'full_time' } },
    { key: 'partTime', params: { employmentType: 'part_time' } },
    { key: 'internship', params: { employmentType: 'internship' } },
  ],
  reise: [
    { key: 'bigGroups', params: { guestsMin: '6' } },
    { key: 'cabins', params: { subcategory: 'hytteutleie' } },
  ],
  // Somaliland
  vehicles: [
    { key: 'foreignUsed', params: { subcategory: 'cars', usage: 'foreign_used' } },
    { key: 'rightHand', params: { subcategory: 'cars', steering: 'right' } },
    { key: 'automatic', params: { subcategory: 'cars', gearbox: 'automatic' } },
  ],
  property: [
    { key: 'forRent', params: { subcategory: 'houses-rent' } },
    { key: 'threeBedrooms', params: { subcategory: 'houses-rent', bedroomsMin: '3' } },
    { key: 'plots', params: { subcategory: 'land' } },
  ],
  phones: [
    { key: 'iphones', params: { subcategory: 'mobile-phones', brand: 'apple' } },
    { key: 'new', params: { condition: 'new' } },
    { key: 'under100', params: { priceMax: '100' } },
  ],
  electronics: [
    { key: 'solarKits', params: { subcategory: 'solar-power', itemType: 'kit' } },
    { key: 'laptops', params: { subcategory: 'computers', itemType: 'laptop' } },
  ],
  livestock: [
    { key: 'camels', params: { subcategory: 'camels' } },
    { key: 'goats', params: { subcategory: 'goats-sheep' } },
  ],
  jobs: [
    { key: 'fullTime', params: { employmentType: 'full_time' } },
    { key: 'ngo', params: { subcategory: 'ngo-jobs' } },
  ],
};
